name: Test Workflow

on: [push, pull_request]

permissions:
  contents: read
  packages: read

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "16"

            - name: Install dependencies
              run: npm install

            - name: Run tests (Unit, Cypress E2E and Component)
              run: npm test